spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/sample?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true'
    username: "root"
    password: "root"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
